name: 'Java Build and Test Action'
description: 'A custom GitHub Action to build and test a Java application using Maven'
author: 'Muhammad Wara'

runs:
  using: 'docker'
  image: 'Dockerfile'  # This points to your Dockerfile in the root of the repository

inputs:
  java-version:
    description: 'The version of Java to use'
    required: true
    default: '11'

outputs:
  result:
    description: 'Build and test result'
    value: 'success'
